name: Continuous integration

on:
  push:
  pull_request:
    branches:
      - develop
      - main

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: '8.0'

      - name: Validate composer.json and composer.lock
        run: composer validate --strict


      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --no-suggest

      - name: Check code style
        run: composer run-script php-cs-fixer-check

      - name: Generate key
        run: php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite

      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: composer run-script testdox

      - name: Fix code coverage paths for Sonar
        run: sed -i 's/\/home\/runner\/work\/escuela-php-panel\/escuela-php-panel\//\/github\/workspace\//g' phpunit.coverage.xml

      - name: Upload coverage
        run: bash <(curl -s https://codecov.io/bash)
